package tazmanianmonster.lab2;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Datoteka")
public class Datoteka implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private tazmanianmonster.lab2.Datoteka datotekaID;

   public Datoteka()
   {
   }

   public tazmanianmonster.lab2.Datoteka getDatotekaID()
   {
      return this.datotekaID;
   }

   public void setDatotekaID(tazmanianmonster.lab2.Datoteka datotekaID)
   {
      this.datotekaID = datotekaID;
   }

   public Datoteka(tazmanianmonster.lab2.Datoteka datotekaID)
   {
      this.datotekaID = datotekaID;
   }

}