package tazmanianmonster.lab2;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Konekcija implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Konekcija() {
    }

}