package tazmanianmonster.lab2;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Konekcija implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Konekcija uspje\u0161no uspostavljena!")
   private java.lang.Boolean konekcijaID;

   public Konekcija()
   {
   }

   public java.lang.Boolean getKonekcijaID()
   {
      return this.konekcijaID;
   }

   public void setKonekcijaID(java.lang.Boolean konekcijaID)
   {
      this.konekcijaID = konekcijaID;
   }

   public Konekcija(java.lang.Boolean konekcijaID)
   {
      this.konekcijaID = konekcijaID;
   }

}