package tazmanianmonster.lab2;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Status prijave")
public class StatusPrijave implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Status")
   private java.lang.Boolean statusID;

   public StatusPrijave()
   {
   }

   public java.lang.Boolean getStatusID()
   {
      return this.statusID;
   }

   public void setStatusID(java.lang.Boolean statusID)
   {
      this.statusID = statusID;
   }

   public StatusPrijave(java.lang.Boolean statusID)
   {
      this.statusID = statusID;
   }

}